#!/usr/bin/env bash
# install mopidy from source as per http://mopidy.readthedocs.org/en/latest/installation/source/

set -e

export DEBIAN_FRONTEND=noninteractive

apt-get -qq update
apt-get -qq install build-essential python-dev python-setuptools
apt-get -qq install python-gst-1.0 gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0 gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-tools
easy_install pip
pip install mopidy


mkdir -p /root/.config/mopidy/
cp /vagrant/other/mopidy.conf /root/.config/mopidy/mopidy.conf
cp /vagrant/other/rc.local /etc/rc.local
