#!/usr/bin/env bash
# install mopidy from source as per http://mopidy.readthedocs.org/en/latest/installation/source/

set -e

export DEBIAN_FRONTEND=noninteractive

wget -q -O - https://apt.mopidy.com/mopidy.gpg | sudo apt-key add -
wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/jessie.list
apt-get -qq update
apt-get -qq install mopidy

systemctl enable mopidy
systemctl start mopidy

cp /vagrant/other/mopidy.conf /etc/mopidy/mopidy.conf
