#!/usr/bin/env bash

set -e

export DEBIAN_FRONTEND=noninteractive

apt-get -qq install python-setuptools
easy_install pip

pip install Mopidy-MusicBox-Webclient
pip install youtube-dl Mopidy-Youtube

apt-get -qq install gstreamer1.0-plugins-bad

systemctl restart mopidy
